# Recitation 0H Debugging
Debugging your code is an indispensable skill when training a model. 


#  Debugging

We will discuss three different ways to debug:
- Print
- Logging
- Python Debugger (Pdb)

**1. Print**

In [ ]:
import torch  
import numpy as np
import random

n_vector = np.random.rand(random.randint(1,5), random.randint(1,5))

print('Numpy array: ')
print("Shape of n_vector: {}".format(n_vector.shape))
print("Type of n_vector: {}".format(type(n_vector)))
print("Data type of n_vector: {}\n".format(n_vector.dtype))

t_vector = torch.from_numpy(n_vector)

print('Torch tensor: ')
print("Shape of t_vector: {}".format(t_vector.shape))
print("Type of t_vector: {}".format(type(t_vector)))
print("Data type of t_vector: {}".format(t_vector.dtype))

Numpy array: 
Shape of n_vector: (1, 4)
Type of n_vector: <class 'numpy.ndarray'>
Data type of n_vector: float64

Torch tensor: 
Shape of t_vector: torch.Size([1, 4])
Type of t_vector: <class 'torch.Tensor'>
Data type of t_vector: torch.float64


In [ ]:
import numpy as np
import random 

length = random.randint(5,7)
data = np.random.rand(length)
print('Original data:\n {}'.format(data))

sum = 0
result = np.zeros(length)
for i in range(length):
  sum += data[i]
  result[i] = sum
  print('Result in {}-th iteration:\n {}'.format(i, result))


Original data:
 [0.98463579 0.49227233 0.56019981 0.59206509 0.21016611 0.84310168]
Result in 0-th iteration:
 [0.98463579 0.         0.         0.         0.         0.        ]
Result in 1-th iteration:
 [0.98463579 1.47690812 0.         0.         0.         0.        ]
Result in 2-th iteration:
 [0.98463579 1.47690812 2.03710793 0.         0.         0.        ]
Result in 3-th iteration:
 [0.98463579 1.47690812 2.03710793 2.62917302 0.         0.        ]
Result in 4-th iteration:
 [0.98463579 1.47690812 2.03710793 2.62917302 2.83933913 0.        ]
Result in 5-th iteration:
 [0.98463579 1.47690812 2.03710793 2.62917302 2.83933913 3.68244082]


**2. Logging**

Logging is  more  powerful than print statements. 
Both logging and print statements allow to us to check whether the code is working, but logging has some additional advantages: 
- Logging uses severity levels to differentiate  which messages are  important and  which are not. 
- Logging allows to print to a file such that you can leave behind breadcrumbs to trace back to the point where the code breaks. 
-  Logging can give context information like time and file name etc.

https://akshatgupta57.medium.com/logging-in-python-a-gentle-introduction-63150cd297d0

In [ ]:
import numpy as np
import  random 
import logging

#Configuring logger
MSGFORMAT = '%(asctime)s  ::  %(levelname)s   :  %(message)s'
DATEFMT = '%m/%d/%Y %I:$M:%S  %p' 
logging.basicConfig(level = logging.WARNING, format = MSGFORMAT, datefmt = DATEFMT)

length = random.randint(5,7)
data = np.random.rand(length)
logging.warning('Original data:\n {}'.format(data))

sum = 0 
result = np.zeros(length)
for i in range(length):
  sum += data[i]
  result[i] = sum
  logging.warning('Result in {}-th iteration:\n {}'.format(i, result))

 [0.2192342  0.86467726 0.47783085 0.0825904  0.71537933 0.30814816]
 [0.2192342 0.        0.        0.        0.        0.       ]
 [0.2192342  1.08391146 0.         0.         0.         0.        ]
 [0.2192342  1.08391146 1.56174231 0.         0.         0.        ]
 [0.2192342  1.08391146 1.56174231 1.64433271 0.         0.        ]
 [0.2192342  1.08391146 1.56174231 1.64433271 2.35971205 0.        ]
 [0.2192342  1.08391146 1.56174231 1.64433271 2.35971205 2.66786021]


**3.  Python Debugger (Pdb)**

In [ ]:
import pdb
import numpy as np
import random

length = random.randint(5,7)
data = np.random.rand(length)
print('Original data:\n {}'.format(data))

sum = 0
result = np.zeros(length)
for i in range(length):
  # pdb.set_trace()
  sum += data[i]
  result[i] = sum
  print('Result in {}-th iteration:\n {}'.format(i, result))
  

Original data:
 [0.21436657 0.89327575 0.53939714 0.83764942 0.26559728]
Result in 0-th iteration:
 [0.21436657 0.         0.         0.         0.        ]
Result in 1-th iteration:
 [0.21436657 1.10764232 0.         0.         0.        ]
Result in 2-th iteration:
 [0.21436657 1.10764232 1.64703946 0.         0.        ]
Result in 3-th iteration:
 [0.21436657 1.10764232 1.64703946 2.48468887 0.        ]
Result in 4-th iteration:
 [0.21436657 1.10764232 1.64703946 2.48468887 2.75028615]
